name: Code Coverage

# Run CI task on Push only for main branch, also on PR. 
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-coverage:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Run Tests
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: ./gradlew app:coveralls

      - name: Upload Coverage Report
        uses: coverallsapp/github-action@v2